- invoke-vmsnapbyfolder.ps1
added to take an ondemand snapshot for any vms within a specified folder.
> invoke-vmsnapbyfolder.ps1 

- Create-SecurePasswordFile.ps1
- Export-RubrikDatabasesJob.ps1
- Export-RubrikDatabasesJobFile.json
Added Export-RubrikDatabaseJob.ps1 for customer request. Also added Create-SecurePasswordFile.ps1 and Export-RubrikDatabasesJobFile.json as supporting files.
> Export-RubrikDatabaseJob and scripts

- Unprotect-DatabaseSnapshotsInRubrik.ps1
Script was created to get around a bug where we try to backup database snapshots if they are protected. This script will unprotect each snapshot
> New Script to unprotect db Snapshots

- Invoke-OnDemandSnapshotToSLA.ps1
This script generically makes snapshots for clients in one or more SLAs using another SLA. It is designed to provide periodic (Monthly, Yearly) snapshots on a scheduled basis. Typically these snapshots would be archived to another location by the target SLA.
> Initial Release

- DBSizingQueries/CollectSQLProfile.ps1
- DBSizingQueries/RubrikSQLProfile-EnterpirseFeatures.sql
- Start-RubrikDBBackup.ps1
Will run backups against multiple databases at once using Rubrik
> Start-RubrikDBBackup

- Alert-RubrikDatabaseMissedLogBackup.ps1
Script to write to the event log if Rubrik misses a log backup
> Alert-RubrikDatabaseMissedLogBackups

- Export-RubrikDatabasesJob.ps1
- Export-RubrikDatabasesJobFile.json
Added ability to restore from a Availability Group
Updated code to better handle an existing database.
Handles instances much better now.
> New Functionality

- Start-RubrikDBMigration.ps1
Script to migrate databases from one server to another via Rubrik
> Migrate databases using Rubrik

- Reporting/check-index-status.ps1
- Reporting/check_last_backup_time.ps1
- Reporting/check_snapshot_archive_status.ps1
- Reporting/get_failed_backups.ps1
- Reporting/get_failed_backups_basic.ps1
- Reporting/get_reportdata_table_41.ps1
- Reporting/per_org_cap_report.ps1
- Reporting/sla_report.ps1
Added a bunch of reporting scripts to help out other PS users
> Added demonstrative reporting scripts

- Reporting/get_all_backup_events.ps1
Adding new script to grab last successful backup event data for all types of VMs, MSSQL, Filesets and Hosts and dumps info into a CSV.
> Adding get_all_backup_events.ps1

- Reporting/get_all_backup_events.ps1
Updated to align with customer requirements
> Updating get_all_backup_events.ps1

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
> Update issue templates

- Get-Archive-Backlog.ps1
This script will locate snapshots that have not been archived and report on them.
> Script to find snapshots that have not been archived. 

- hyper-v-vtpm/export-vtpm-guardian-certs.ps1
- hyper-v-vtpm/import-vtpm-guardian-certs.ps1
Scripts to allow vTPM support with Rubrik
Adding in README in next commit
> Adding Hyper-V vTPM Scripts

- VMDKRecovery.ps1
- VolumeRecovery.ps1
An easy way to select a snapshot of a VM from a specific day and mount a single VMDK or all VMDKs to another VM.
> Mount one or more VMDK(s) to another VM

- .gitignore
- Reporting/get_archive_report.ps1
New Script - Report last completed archival of snap by object
- [x ] New feature (non-breaking change which adds functionality)
> Archive report

- VMDKRecovery.ps1
- VolumeRecovery.ps1
Small improvements after I got some feedback
In my lab
> small improvments

- Start-RubrikDBLogBackup.ps1
Start-RubrikDBLogBaackup
Created a new script to handle transaction log backups of a entire server or group.
In Start-RubrikDBBackup, i cleaned up some of the comments
Please describe your pull request in detail.
This project only accepts pull requests related to open issues.
* If suggesting a new feature or change, please discuss it in an issue first.
* If fixing a bug, there should be an issue describing it with steps to reproduce
_Please link to the issue here_
Why is this change required? What problem does it solve?
* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code, etc.
What types of changes does your code introduce? Put an `x` in all the boxes that …
> RubrikDB*Backup

- Export-RubrikDatabasesJob.ps1
Error handling for FINISHING state that seems to run beyond the completion of the Export
Script sits at "FINISHING" status on the job for an extended period. Added "FINISHING" as an accepted loop end so that the script can complete quicker
> Added FINISHING

- sla_report.ps1
`sla_report.ps1` was not working with Advanced SLAs.
Added handling for v2 SLA Domains to correctly render retention details.
Tested in internal lab on 5.x.
> updated sla_report.ps1 for 5.x

- vCloudDirector/README.md
- vCloudDirector/backup_vcd_vapp_metadata.ps1
- vCloudDirector/restore_vcd_vapp_metadata.ps1
Adding a pre-script for Rubrik to capture vCD vApp Metadata and a restore script to restore it back to the vApp
Captures vApp Metadata as part of the protection for vApps
Ran in Powershell against a vCD Cell and relevant metadata stored in CSV
> vCloud Director Metadata Scripts

- Reporting/missed_snapshots_envision.ps1
New script to get all missed snapshots from the missed_snapshot endpoint against MSSQL, VMs and Filesets.
Example script to show ability to automate and see missed snapshots from the SLA window (3 attempts with no success)
Ran against Rubrik Lab Clusters
> Add Envision Missed Snapshot report

- Invoke-AzureBlobsProtect.ps1
Original use case was a prospect who had the need to protect internal databases etc. within Azure Stack. Backups is stored in the local Storage Account and we use AzCopy to protect the data within the Blob and combine it with our capabilities in Managed Volumes.
Prospect gets encryption, reporting, SLA Compliance etc. on the protected data.
This project only accepts pull requests related to open issues.
* If suggesting a new feature or change, please discuss it in an issue first.
* If fixing a bug, there should be an issue describing it with steps to reproduce
_Please link to the issue here_
Why is this change required? What problem does it solve?
* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to see how your …
> AzCopy contents of a given Azure Blobs Container to a Rubrik Managed Volume (EAS)

- DBSizingQueries/Parse-RubrikSizing.ps1
- MSSQL/Create-SecurePasswordFile.ps1
Addresses issue #89 
I have converted the script to use the more standard usage of Export-CLIXml. 
Addresses issue #83 
I have corrected the header record so it will the correct column headers when processing data.
> Converted to use Export-CLIXml

- MSSQL/invoke-RubrikDatabaseAGRefresh.ps1
Based on parameters supplied, RubrikDatabaseAGRefresh will restore databases from a Source (eg. Production to a target server (eg. Developer)
Created to automate the AG environment refresh, for example, DevRefresh 
Tested at Ranger Lab.
> Script to refresh AG databases

- MSSQL/Start-RubrikDBBackup.ps1
Fixed bug with Providing SLA domain
> Fixed bug with Providing SLA domain

- Install-RubrikBackupService.ps1
Having Install-RubrikBackupService confirming the machine in DNS and checking if the machine is up/down prior start installing the RBS
related to the issue #81 
Tested at Ranger lab
> Having Install-RubrikBackupService confirming the machine in DNS

- Reporting/get-SnapshotRetention.ps1
Script to create a CSV report with Retention Snapshot information
It was tested at Ranger Lab
> Script to create a CSV report with Retention Snapshot information

- MSSQL/invoke-MassLiveMount.ps1
- MSSQL/invoke-MassUnMount.ps1
fixed issue with sql named instances parameters
Tested at Ranger LAB
> fixed issue with sql named instances parameters

- .gitignore
- Reporting/get-protection-events-servers.ps1
Reporting script to isolate results to a subset of servers and produce an HTML file and email report
Specific ask for this
Tested in Gaia lab
> Add New Reporting script

- MV/SAP-workflow.ps1
New script to start a workflow to create customer MVs for SAP database backups
Customer Request.
Run multiple times against Gaia lab.
> Adding script for SAP Workflows and MV

- MV/SAP-workflow.ps1
Few fixes on sap-workflow-script
Gaia lab
> Add SLA to be local only

- MV/SAP-workflow.ps1
Fix issues with SAP script to support basic parsing on the native API calls, format and display data into handled output
Customer Request.
Tested in Gaia lab.
> Add support for additional channels

- MV/SAP-workflow.ps1
Add a create-MV function to allow us to set an exportConfig due to issues highlighted in https://github.com/rubrikinc/rubrik-sdk-for-powershell/issues/464
https://github.com/rubrikinc/rubrik-sdk-for-powershell/issues/46
Tested in Full in Gaia
> Updated SAPMV script to fix MV bug

- MSSQL/Restore-RubrikDatabasesJob.ps1
- Reporting/DatabaseBackupReport.ps1
Database Backup Report to show if database is compliant or based on backups taken. 
No issue, this is new functionality
No issue, this is new functionality
Script has been tested internally as well as by several customers. 
> Database Backup Report

- MSSQL/invoke-RubrikDatabaseAGRefresh.ps1
Changed the script to support AG AUTO SEED and also support CDM 5.1
Support AG AUTO SEED and CDM 5.1
Tested on Rangers LAB for 5.0 and GAIA for 5.1
> changed the script to support AG AUTO SEED and support 5.1.

- MSSQL/Prepare-ExportDatabaseJobFile.ps1
Prepare-ExportRubrikDatabaseJob.ps1 had a bug with the parameter of last full where we would try to convert dates that didnt need to. 
The conversion of dates has been removed since we are also now using the new Get-RubrikDatabaseRecoveryPoint cmdlet which automatically fixes dates and leaves them in UTC
> Fixed bug with LastFull

- Reporting/Get-RubrikRecentOnDemandSnapshot.ps1
I created a function that reports on all on-demand backups for the last month and the user which initiated them.
Resolve #140
For reporting purposes
Ran against 5.1 cluster and validated results
> Added Get-RubrikRecentOnDemandSnapshot to Reporting

- MSSQL/Cutover a db into an AG.ps1
- MSSQL/Invoke-LogShippingFailover.ps1
Two scripts that work with log shipping
One fails over and reverses the log shipping direction and the other is used as an example migration script
No issue....just new scripts i wrote for customers
* If suggesting a new feature or change, please discuss it in an issue first.
* If fixing a bug, there should be an issue describing it with steps to reproduce
Wrote scripts in response to customer requests
Tested in Gaia and in customers own environments. Scripts have been already used in production environments
* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code, etc.
Go over …
> Two scripts that work with log shipping

- MSSQL/Invoke-RubrikDatabaseAGSeed.ps1
I added 2 validations
1- Check if the given DB has at least a full bkp (snapshot)
2- Check if the AG is AUTO SEED ON, if so, will join the DB on AG only at Primary Replica.
#136 
This project only accepts pull requests related to open issues.
I tested on Rangers lab
> fixed missing validation as issue #136

- Reporting/get-protection-events-servers.ps1
Fix script `get-protection-events-servers.ps1`
https://github.com/rubrikinc/rubrik-scripts-for-powershell/issues/152
Tested against 5.1 and 5.2 clusters
> Fix get-protection-events-servers.ps1

- Reporting/get-protection-events-servers.ps1
Fix issue with detecting report
Bug found with script.
Local lab on latest powershell module
> Fix issue with Report

- MISC/Run-iPerfTest.ps1
> initial commit of Run-iPerfTest.ps1

- Sizing/DBSizingQueries/CollectSQLProfile.ps1
Convert SQL Authentication to use a Credential instead of clear text password. I also changed the script to try to connect to the target server first as a test using the credential. Before it would only connect via NT Authentication.
> Convert SQL Authentication to use a Credential instead of clear text password

- VM/create_vCenter_User.ps1
This PR includes the final additions to the permissions list for new AppFlows v1 functionality.  Additionally, there were some cleanup items handled including an update to the $usage and $example items to match the script's file name.  Other typos and formatting items were also corrected/adjusted.
https://github.com/rubrikinc/rubrik-scripts-for-powershell/issues/187
This addition of permissions is required to ensure smooth operation for CDM interactions used by Polaris AppFlows for orchestrated disaster recovery.
This script has been used successfully in the RTT AppFlows Lab and with two new customers with success in all cases.
- [ x] Bug fix (non-breaking change which fixes an issue)
Go over all the …
> Additional missing AppFlows permissions

- Reporting/Get-CapacityChangeReport.ps1
Add 'Get-CapacityChangeReport.ps1'
New script
The 'Get-CapacityChangeReport.ps1' script calculates the change (growth) in object capacity between one or more dates. A html report summary with the top objects and CSV report with the details is generated.
> Add Get-CapacityChangeReport.ps1
